name: foundr with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        foundr-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use foundr.js ${{ matrix.foundr-version }}
      uses: actions/setup-foundr@v3
      with:
        foundr-version: ${{ matrix.foundr-version }}

    - name: Build
      run: |
        npm install
        npx webpack
